// AUTO-GENERATED by scripts/wiki-generate.mjs - do not hand-edit.
// Source of truth is the adjacent .generated.json sidecar. This checked-in
// copy is an empty placeholder so the template builds standalone before
// the generator has run for a given repo.
import type { EndpointGroup } from '../types';
import data from './endpoints.generated.json';

export const endpointGroups = data as unknown as EndpointGroup[];

export function getGroup(slug: string) {
  return endpointGroups.find((g) => g.slug === slug);
}
