// AUTO-GENERATED by scripts/wiki-generate.mjs from wiki.config.yaml's
// enabled extractors - do not hand-edit. This checked-in copy is a
// Home-only placeholder so the template builds standalone before the
// generator has run for a given repo.
import type { NavSection } from '../types';

export const topNav: { title: string; href: string }[] = [{ title: 'Home', href: '/' }];

export const sidebarSections: Record<string, NavSection> = {};

export function sectionKeyForPath(_pathname: string): string {
  return Object.keys(sidebarSections)[0] ?? '';
}
