// AUTO-GENERATED by scripts/wiki-generate.mjs - do not hand-edit.
// Source of truth is the adjacent .generated.json sidecar. This checked-in
// copy is an empty placeholder so the template builds standalone before
// the generator has run for a given repo.
import type { MarkdownPageDoc } from '../types';
import data from './pages.generated.json';

export const markdownPages = data as unknown as MarkdownPageDoc[];

export function getPage(slug: string) {
  return markdownPages.find((p) => p.slug === slug);
}
