// AUTO-GENERATED by scripts/wiki-generate.mjs - do not hand-edit.
// Source of truth is the adjacent .generated.json sidecar, which IS safe
// (and expected) to be hand-edited between generator runs - the merge
// logic in scripts/wiki-extractors/merge.mjs never overwrites or removes
// entries whose extracted source content has not changed.

import type { SkillDoc } from '../types';
import data from './skills.generated.json';

export const skills = data as unknown as SkillDoc[];

export function getSkill(slug: string) {
  return skills.find((s) => s.slug === slug);
}
