// AUTO-GENERATED by scripts/wiki-generate.mjs - do not hand-edit.
// Source of truth is the adjacent .generated.json sidecar. This checked-in
// copy is an empty placeholder so the template builds standalone before
// the generator has run for a given repo.
import type { TestSuiteDoc } from '../types';
import data from './tests.generated.json';

export const testSuites = data as unknown as TestSuiteDoc[];

export function getTestSuite(slug: string) {
  return testSuites.find((t) => t.slug === slug);
}
