// AUTO-GENERATED by scripts/wiki-generate.mjs - do not hand-edit.
// Source of truth is the adjacent .generated.json sidecar. This checked-in
// copy is an empty placeholder so the template builds standalone before
// the generator has run for a given repo.
import type { WorkflowDoc } from '../types';
import data from './workflows.generated.json';

export const workflows = data as unknown as WorkflowDoc[];

export function getWorkflow(slug: string) {
  return workflows.find((w) => w.slug === slug);
}
