// AUTO-GENERATED by scripts/wiki-generate.mjs from wiki.config.yaml - do not hand-edit.
// Every value here is a literal copied from wiki.config.yaml - never LLM-generated.

export const wikiConfig = {
  "title": "agent-ops Docs",
  "description": "Documentation for agent-ops: the pipeline orchestrator, shared skills, and CI/CD workflows.",
  "theme": {
    "accent": "#14b8a6",
    "accentHover": "#0f9488",
    "accentMuted": "rgba(20, 184, 166, 0.1)"
  },
  "favicon": "/favicon.svg",
  "githubUrl": "https://github.com/HeyItsChloe/agent-ops",
  "proxyBaseUrl": "",
  "targetApiBaseUrl": ""
} as const;
