// AUTO-GENERATED by scripts/wiki-generate.mjs - do not hand-edit.
// Source of truth is the adjacent .generated.json sidecar. This checked-in
// copy is an empty placeholder so the template builds standalone before
// the generator has run for a given repo.
import type { AppDoc } from '../types';
import data from './apps.generated.json';

export const apps = data as unknown as AppDoc[];

export function getApp(slug: string) {
  return apps.find((a) => a.slug === slug);
}
