// AUTO-GENERATED by scripts/wiki-generate.mjs - do not hand-edit.
// Source of truth is the adjacent .generated.json sidecar. This checked-in
// copy is an empty placeholder so the template builds standalone before
// the generator has run for a given repo.
import type { AutomationDoc } from '../types';
import data from './automation.generated.json';

export const automation = data as unknown as AutomationDoc[];

export function getAutomation(slug: string) {
  return automation.find((a) => a.slug === slug);
}
