// AUTO-GENERATED by scripts/wiki-generate.mjs - do not hand-edit.
// Source of truth is the adjacent .generated.json sidecar, which IS safe
// (and expected) to be hand-edited between generator runs - the merge
// logic in scripts/wiki-extractors/merge.mjs never overwrites or removes
// entries whose extracted source content has not changed.

import type { ChangelogEntry } from '../types';
import data from './changelog.generated.json';

export const changelog = (data as unknown as ChangelogEntry[]).slice().sort((a, b) => (a.date < b.date ? 1 : -1));
