// AUTO-GENERATED by scripts/wiki-generate.mjs - do not hand-edit.
// Source of truth is the adjacent .generated.json sidecar, which IS safe
// (and expected) to be hand-edited between generator runs - the merge
// logic in scripts/wiki-extractors/merge.mjs never overwrites or removes
// entries whose extracted source content has not changed.

import type { FeatureDoc } from '../types';
import data from './features.generated.json';

export const features = (data as unknown as FeatureDoc[]).slice().sort((a, b) => a.order - b.order);

export function getFeature(slug: string) {
  return features.find((f) => f.slug === slug);
}
