// AUTO-GENERATED by scripts/wiki-generate.mjs - do not hand-edit.
// Source of truth is the adjacent .generated.json sidecar, which IS safe
// (and expected) to be hand-edited between generator runs - the merge
// logic in scripts/wiki-extractors/merge.mjs never overwrites or removes
// entries whose extracted source content has not changed.

import type { IntegrationDoc } from '../types';
import data from './integrations.generated.json';

export const integrations = data as unknown as IntegrationDoc[];

export function getIntegration(slug: string) {
  return integrations.find((i) => i.slug === slug);
}
