// AUTO-GENERATED by scripts/wiki-generate.mjs from wiki.config.yaml's enabled extractors - do not hand-edit.

import type { NavSection } from '../types';
import { workflows } from './workflows';
import { markdownPages } from './pages';

export const topNav: { title: string; href: string }[] = [
  { title: 'Home', href: '/' },
  { title: 'CI/CD', href: '/ci-cd' },
  { title: 'Docs', href: '/docs' },
];

export const sidebarSections: Record<string, NavSection> = {
  'ci-cd': { title: 'CI/CD', href: '/ci-cd', children: workflows.map((w) => ({ title: w.title, href: `/ci-cd/${w.slug}` })) },
  'docs': { title: 'Docs', href: '/docs', children: markdownPages.map((p) => ({ title: p.title, href: `/docs/${p.slug}` })) },
};

export function sectionKeyForPath(pathname: string): string {
  const seg = pathname.split('/').filter(Boolean)[0] ?? '';
  return Object.keys(sidebarSections).includes(seg) ? seg : Object.keys(sidebarSections)[0];
}
