// AUTO-GENERATED by scripts/wiki-generate.mjs - do not hand-edit.
// Source of truth is the adjacent .generated.json sidecar, which IS safe
// (and expected) to be hand-edited between generator runs - the merge
// logic in scripts/wiki-extractors/merge.mjs never overwrites or removes
// entries whose extracted source content has not changed.

import type { WorkflowDoc } from '../types';
import data from './workflows.generated.json';

export const workflows = data as unknown as WorkflowDoc[];

export function getWorkflow(slug: string) {
  return workflows.find((w) => w.slug === slug);
}
