// Backs the `scaffold_project` MCP tool (§5.1, §6.1). Onboarding a new dev
// or personal project is a pipeline capability, not a static template a
// human copies by hand: this generates the new project's skill file,
// appends its registry entry, and — for a dev project — writes the thin
// per-repo caller workflow, all in one action.
//
// Assumes the GitHub App installation covers both the control repo and any
// target app repo (an org-wide install). If a target repo hasn't had the
// App installed yet, the write to that repo will fail — install it first
// (roadmap Phase 8, step 1).
import YAML from "yaml";
import { createOrUpdateFile, getInstallationToken, type GitHubAppConfig } from "../integrations/github.js";
import { logger } from "../logging.js";
import type { ProjectEntry } from "../types.js";

export interface ScaffoldRequest {
  name: string;
  type: "dev" | "personal";
  repo?: string; // "owner/name" — required when type is "dev"
  modelProfile?: string;
}

export interface ScaffoldDeps {
  githubApp: GitHubAppConfig;
  installationId: string;
  controlRepoOwner: string;
  controlRepoName: string;
  branch: string;
}

const REGISTRY_PATH = "orchestrator/src/registry/projects.yaml";

export async function scaffoldProject(deps: ScaffoldDeps, req: ScaffoldRequest): Promise<void> {
  if (req.type === "dev" && !req.repo) {
    throw new Error("scaffold_project: 'repo' is required for type 'dev'");
  }
  const log = logger.withContext({ project: req.name, type: req.type });

  const token = await getInstallationToken(deps.githubApp, deps.installationId);
  const skillFolder = req.type === "dev" ? `skills/${req.name}` : `skills/personal/${req.name}`;

  log.info("writing new project skill");
  await createOrUpdateFile(
    token,
    deps.controlRepoOwner,
    deps.controlRepoName,
    `${skillFolder}/SKILL.md`,
    skillTemplate(req.name, req.type),
    `Scaffold ${req.name} project skill`,
    deps.branch,
  );

  log.info("appending registry entry");
  const entries = await readRegistry(token, deps.controlRepoOwner, deps.controlRepoName, deps.branch);
  entries.push({
    project: req.name,
    type: req.type,
    ...(req.repo ? { repo: `github.com/${req.repo}` } : {}),
    model_profile: req.modelProfile ?? (req.type === "dev" ? "implementation" : "planning"),
    skill_folder: skillFolder,
  });
  await createOrUpdateFile(
    token,
    deps.controlRepoOwner,
    deps.controlRepoName,
    REGISTRY_PATH,
    YAML.stringify(entries),
    `Register ${req.name} project`,
    deps.branch,
  );

  if (req.type === "dev" && req.repo) {
    const [owner, repo] = req.repo.split("/");
    log.info("writing caller workflow", { repo: req.repo });
    await createOrUpdateFile(
      token,
      owner,
      repo,
      ".github/workflows/dev-pipeline.yml",
      callerWorkflowTemplate(skillFolder, deps.controlRepoOwner, deps.controlRepoName),
      `Add dev-pipeline caller workflow for ${req.name}`,
      deps.branch,
    );
  }
}

async function readRegistry(token: string, owner: string, repo: string, branch: string): Promise<ProjectEntry[]> {
  const res = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${REGISTRY_PATH}?ref=${branch}`, {
    headers: { Authorization: `Bearer ${token}`, Accept: "application/vnd.github.raw" },
  });
  if (res.status === 404) return [];
  if (!res.ok) throw new Error(`failed to read registry: ${res.status} ${await res.text()}`);
  const raw = await res.text();
  return raw.trim() ? ((YAML.parse(raw) as ProjectEntry[]) ?? []) : [];
}

function skillTemplate(name: string, type: "dev" | "personal"): string {
  return [
    `# ${name}`,
    "",
    "Generated by the `project-scaffold` skill (skills/shared/project-scaffold/SKILL.md).",
    "Fill in before relying on this project:",
    "",
    "- Conventions: <coding style, folder layout, naming>",
    "- Test framework and command: <e.g. \"npm test -- --coverage\">",
    "- PR / approach-doc expectations: see skills/shared/approach-doc-format/SKILL.md",
    "- Approval-gate behavior: see skills/shared/approval-gate-protocol/SKILL.md",
    "- Guardrails: <anything this project must never do unattended>",
    ...(type === "dev"
      ? ["- CI: paired with a thin caller workflow that calls agent-ops's dev-pipeline-reusable.yml"]
      : []),
    "",
  ].join("\n");
}

function callerWorkflowTemplate(skillFolder: string, controlRepoOwner: string, controlRepoName: string): string {
  return `name: dev-pipeline

on:
  issues:
    types: [labeled]
  issue_comment:
    types: [created]
  repository_dispatch:
    types: [agent-trigger]

jobs:
  dispatch:
    # id-token: write must be granted here too — reusable workflow permissions
    # are the intersection of caller + callee, and dev-pipeline-reusable.yml's
    # jobs request id-token: write for anthropics/claude-code-action@v1's OIDC.
    permissions:
      contents: read
      packages: read
      id-token: write
    uses: ${controlRepoOwner}/${controlRepoName}/.github/workflows/dev-pipeline-reusable.yml@main
    with:
      project_language: CHANGE_ME
      test_command: CHANGE_ME
      coverage_type: CHANGE_ME
      desired_coverage: 85
      skill_folder: ${skillFolder}
      reviewer: heyitschloe
      action: >-
        \${{
          (github.event.label.name == 'approach-ready' && 'plan') ||
          (github.event.label.name == 'approved' && 'implement') ||
          (contains(github.event.comment.body, '@dev-agent plan') && 'plan') ||
          (contains(github.event.comment.body, '@dev-agent implement') && 'implement') ||
          github.event.client_payload.action
        }}
    secrets: inherit
`;
}
