// AUTO-GENERATED by scripts/wiki-generate.mjs from wiki.config.yaml - do
// not hand-edit. This checked-in copy is a placeholder so the template
// builds standalone before the generator has run for a given repo. Every
// value here is a literal copied from wiki.config.yaml - never LLM-generated.
export const wikiConfig = {
  title: 'Wiki',
  description: '',
  theme: {
    accent: '#5169dd',
    accentHover: '#4257c4',
    accentMuted: 'rgba(81, 105, 221, 0.1)',
  },
  favicon: '/favicon.svg',
  githubUrl: '',
  proxyBaseUrl: '',
  targetApiBaseUrl: '',
} as const;
